
name: Python package



on: [push,pull_request]



jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@master
      
      - name: record current time
        uses: PLATFORM_BINARY_DOWNLOAD_START=$SECONDS
      
      - name: curl to download files
        uses: curl -D headers.txt -SL https://oryxsdksdev.blob.core.windows.net/python/python-3.8.0.tar.gz --output

      - name: calculate elapsed time
        uses: PLATFORM_BINARY_DOWNLOAD_ELAPSED_TIME=$(($SECONDS - $PLATFORM_BINARY_DOWNLOAD_START))

      - name: echo downloading time
        uses: echo "Downloaded in $PLATFORM_BINARY_DOWNLOAD_ELAPSED_TIME sec(s)."
        
        
